Add pagination to homepage transactions
FuelLabs/block-explorer-v2 pull request #62
Opened 2022-05-12 00:33 UTC by LuizAsFight

Enable user to check older transactions with simple pagination

Closes #60

https://user-images.githubusercontent.com/8636507/167968801-8156197e-b49f-4351-b53f-31288f2577dd.mov
https://user-images.githubusercontent.com/8636507/167968810-fc451a44-e295-4fa1-a1c0-8ca56ec3628d.mov

2022-05-12 00:34 UTC, LuizAsFight commented
https://user-images.githubusercontent.com/8636507/167968989-bad28b25-9bb0-4e6e-b506-d13ddc8c5c57.mov

https://user-images.githubusercontent.com/8636507/167969017-4107415f-073b-42c6-b4a2-dd5a45ef8ce1.mov

2022-05-12 01:02 UTC, luizstacio requested changes

2022-05-12 01:02 UTC, luizstacio commented on src/pages/HomePage/RecentTransactions.tsx
>  export function RecentTransactions({ transactions }: Props) {
Would be nice to use pagination directly on the GraphQL queries as our core has this capability.

If you have the network running locally you can access `http://localhost:4000/playground` to see the GraphQL Playground.

## Examples

### First query without cursor query the latest 5 transactions
```
query {
  transactions(last: 5) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
    }
    edges {
      node {
        id
      }
    }
  }
}
```

### Next page query passing the `startCursor`
```
query {
  transactions(last: 5, before: "5#0x8844e7be9a02d03a5681a5b280dc0fc9ac423f50d9c3c9cbfde370d7c11df3e8") {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
    }
    edges {
      node {
        id
      }
    }
  }
}
```

2022-05-13 21:09 UTC, luizstacio commented
We have a issue with paginations when arriving to the last it will be fixed by: https://github.com/FuelLabs/fuel-core/pull/323/files

2022-05-13 21:10 UTC, luizstacio approved these changes
LGTM

2022-05-13 21:32 UTC, merged